version: "3.9"

networks:
  backend:

services:
  php-fpm:
    volumes:
      - ./test:/var/www/test
    build:
      context: ./php-fpm
    networks:
      - backend
    working_dir: /var/www/test
    depends_on:
      - mysql
      - redis
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./test:/var/www/test
    ports:
      - 80:80
      - 443:443
    networks:
      - backend
    depends_on:
      - php-fpm
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
      MYSQL_DATABSE: laravel
    networks:
      - backend
  redis:
    image: redis:7.0.0-bullseye
    networks:
      - backend